language: cpp

branches:
  only:
    - master

dist: bionic


  
addons:
  apt:
    packages:
    - cmake
    - make
    - g++
    - pkg-config

install:
  - pip3 install --user requests

# Build steps
script:
  - ./build_simple.sh
  - cd unit-tests.wsjcpp
  - ./build_simple.sh
  - ./unit-tests
  - cd server-tests
  - ./run_tests.py